language: c
install: bash -e .travis-ci-install.sh
script: bash -e .travis-ci.sh
cache: apt
dist: trusty
sudo: required
matrix:
  include:
  - os: linux
    env: OCAML_VERSION=4.05.0 OPAM_VERSION=1.2.2
  - os: linux
    env: OCAML_VERSION=4.04.2 OPAM_VERSION=1.2.2
  - os: linux
    env: OCAML_VERSION=4.04.1 OPAM_VERSION=1.2.2
  - os: linux
    env: OCAML_VERSION=4.04.0 OPAM_VERSION=1.2.2
